@url = https://mcctest1.cn1.utools.club
@type = Content-Type: application/json
@Authorization= Authorization: Bearer c84e9642-ad87-4e43-aa91-feada951c462

###增加企业
POST {{url}}/enterprise HTTP/1.1
{{type}}

{
  "mobile":"13800000001",
  "password":"123456"
}

###获取企业的全部信息
GET {{url}}/company HTTP/1.1
{{type}}